# Generated by Django 2.2.1 on 2019-06-24 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole', models.CharField(max_length=256, unique=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('hole_pic', models.ImageField(blank=True, upload_to='hole_pic/')),
                ('hole_description', models.TextField(max_length=1024)),
                ('is_private', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hole', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('post', models.TextField(max_length=1024)),
                ('image', models.ImageField(blank=True, upload_to='post_pic/')),
                ('creation_datetime', models.DateTimeField(auto_now=True)),
                ('reply_id', models.PositiveIntegerField(default=0)),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_post', to='forum.Hole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HoleFollower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_follower', to='forum.Hole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
