# Generated by Django 2.2.1 on 2019-06-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfolio',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
