# Generated by Django 2.2.1 on 2019-06-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20190622_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfolio',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pic/'),
        ),
    ]
